[package]
name = "board"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
chrono-tz.workspace = true
chrono.workspace = true
anyhow.workspace = true
clap.workspace = true
ratatui.workspace = true
rush-core = { path = "../rush-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
